[package]
name = "light_sec_agg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13"
rand = "0.7"
rand_distr = "0.3.0"
rayon = "1.4.0"
statrs = "*"